// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pills;

#nullable disable

namespace Pills.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Pills.Models.PillsTaken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PillTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PillTypeId");

                    b.ToTable("PillsTaken");
                });

            modelBuilder.Entity("Pills.Models.PillsTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxAllowed")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PillsTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxAllowed = 1,
                            Name = "Magnesium"
                        },
                        new
                        {
                            Id = 2,
                            MaxAllowed = 1,
                            Name = "VitaminD"
                        },
                        new
                        {
                            Id = 3,
                            MaxAllowed = 5,
                            Name = "Denicit"
                        });
                });

            modelBuilder.Entity("Pills.Models.PillsTaken", b =>
                {
                    b.HasOne("Pills.Models.PillsTypes", "PillType")
                        .WithMany()
                        .HasForeignKey("PillTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PillType");
                });
#pragma warning restore 612, 618
        }
    }
}
